spring:
  application:
    name: store-gateway

  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: classroom-auth
          uri: lb://classroom-auth
          predicates:
            - Path=/auth/**

        - id: classroom-account
          uri: lb://classroom-account
          predicates:
            - Path=/accounts/**

        - id: insper
          uri: https://www.insper.edu.br
          predicates:
            - Path=/

        - id: classroom-aula
          uri: lb://classroom-aula
          predicates:
            - Path=/aulas/**


management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

api:
  endpoints:
    open: >
      POST /auth/register,
      POST /auth/login,
      ANY /auth/actuator,
      ANY /accounts/actuator
