spring:
  application:
    name: store-gateway

  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: classroom-auth
          uri: lb://classroom-auth
          predicates:
            - Path=/auth/**
          filters:
            - name: RewritePath
              args:
                regexp: "/auth/(?<segment>.*)"
                replacement: "/$\\{segment}"
          # Configuração de segurança para restringir acesso com base em roles
          filters:
            - name: Security
              args:
                authorities: ROLE_ADMIN
                
        - id: classroom-account
          uri: lb://classroom-account
          predicates:
            - Path=/accounts/**
          filters:
            - name: RewritePath
              args:
                regexp: "/accounts/(?<segment>.*)"
                replacement: "/$\\{segment}"
          # Configuração de segurança para restringir acesso com base em roles
          filters:
            - name: Security
              args:
                authorities: ROLE_ADMIN

        - id: insper
          uri: https://www.insper.edu.br
          predicates:
            - Path=/

        - id: classroom-aula
          uri: lb://classroom-aula
          predicates:
            - Path=/aulas/**

        - id: classroom-monitoria
          uri: lb://classroom-monitoria
          predicates:
            - Path=/monitorias/**

        - id: classroom-departamento
          uri: lb://classroom-departamento
          predicates:
            - Path=/departamentos/**

management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
