apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: c0d8/gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: eureka.client.service-url.defaultZone
            value: http://10.97.72.208:8761/eureka/