apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: ClusterIP
  ports:
    - port: 8761
      targetPort: 8080
      protocol: TCP
  selector:
    app: gateway